#!/bin/bash

function run {
    printf '%s\n' "$*" > /dev/tty
    "$@"
}

ip=$(< linodes jq -rc ".[] | select(.label | contains(\"$1\")) | .ip_public" | head -n1)
if [ -n "$ip" ]; then
    exec ssh -o UserKnownHostsFile=/dev/null -o 'StrictHostKeyChecking=no' -o PreferredAuthentications=publickey "root@$ip" < /dev/tty
else
    echo no host matches >&2
    exit 1
fi

