# Copyright (C) 2020 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.---

- name: import configurations
  import_playbook: settings.yml

- name: preconfigure linodes
  import_playbook: pre-config.yml

- hosts: all
  become: yes
  tasks:
  - name: fetch cephadm
    become: no
    delegate_to: localhost
    register: cephadm
    run_once: true
    uri:
      force: yes
      mode: 0755
      return_content: yes
      url: "https://download.ceph.com/rpm-{{ RELEASE }}/el9/noarch/cephadm"

  - name: distribute cephadm
    copy:
      dest: /root/cephadm
      group: root
      mode: 0755
      owner: root
      content: "{{ cephadm.content }}"

  - name: create /etc/ceph directory
    file:
      path: /etc/ceph
      state: directory
      owner: root
      group: root
      mode: 0755

- hosts: mon-000
  become: yes
  tasks:
  - name: "add {{ RELEASE }} repos"
    shell: /root/cephadm add-repo {{ CEPHADM_REPO }}

  - name: "install {{ RELEASE }}"
    shell: /root/cephadm install ceph-common

  - name: check ceph installed
    stat:
      path: /etc/ceph/ceph.conf
    register: ceph_installed

  - name: "bootstrap {{ RELEASE }}"
    shell: /root/cephadm bootstrap --allow-fqdn-hostname --mon-ip {{ monitor_address }}
    when: not ceph_installed.stat.exists

  - name: config public network
    shell: ceph config set global public_network 192.168.0.0/16

  - name: config cluster_network
    shell: ceph config set global cluster_network 192.168.0.0/16

  - name: log to files
    shell: ceph config set global log_to_file true

  - name: log cluster to file
    shell: ceph config set global mon_cluster_log_to_file true

  - name: disable stderr logging
    shell: ceph config set global log_to_stderr false

  - name: disable stderr logging of cluster log
    shell: ceph config set global mon_cluster_log_to_stderr false


- hosts: mons mgrs osds mdss grafana-servers
  become: yes
  tasks:
  - name: fetch ceph.pub
    shell: cat /etc/ceph/ceph.pub
    register: ceph_pub
    delegate_to: mon-000
    run_once: true

  - name: register ceph.pub with hosts
    lineinfile:
      path: /root/.ssh/authorized_keys
      line: "{{ ceph_pub.stdout }}"

  - name: set hostname
    shell: hostnamectl set-hostname {{ inventory_hostname }}

  - name: add hostname to cephadm
    shell: ceph orch host add "{{ inventory_hostname }}" "{{ ansible_ssh_host }}"
    delegate_to: mon-000

  - name: label host
    shell: ceph orch host label add "{{ inventory_hostname }}" "{{ ceph_group }}"
    delegate_to: mon-000

- hosts: mon-000
  become: yes
  tasks:
  - name: use labeled mons
    shell: ceph orch apply mon label:mons

  - name: use labeled mgrs
    shell: ceph orch apply mgr label:mgrs

  - name: add osds
    shell:
      cmd: |
        tee /dev/stderr <<EOF | ceph orch apply -i -
        service_type: osd
        service_id: default
        placement:
          label: osds
        data_devices:
          paths:
            - /dev/sdc
        EOF

  - name: use labeled mdss
    shell: ceph orch apply mds all --placement=label:mdss
    when: groups['mdss'] | default([]) | length > 0

- hosts: all
  become: yes
  tasks:
  - name: generate min config
    shell: ceph config generate-minimal-conf
    delegate_to: mon-000
    register: minimal_config
    run_once: true

  - name: setup config
    copy:
      # yay ansible bug: https://github.com/ansible/ansible/issues/6077
      content: "{{ minimal_config.stdout }}\n"
      dest: /etc/ceph/ceph.conf
      owner: root
      group: root
      mode: 0644


- hosts: clients
  become: yes
  tasks:
  - name: "add {{ RELEASE }} repos"
    shell: /root/cephadm add-repo {{ CEPHADM_REPO }}

  - name: "install {{ RELEASE }}"
    shell: /root/cephadm install ceph-common ceph-fuse
