# Copyright (C) 2021 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.---

- hosts: all
  gather_facts: no
  tasks:
  - set_fact:
     # RELEASE must be a tagged version or release branch to pull cephadm from, probably just use the latest release, not main!
     RELEASE: reef
     # CEPHADM_REPO is the branch to actually deploy
     # It can be a dev branch, e.g. CEPHADM_REPO: --dev wip-batrick-testing-20230808.012511
     CEPHADM_REPO: --release reef
