#!/bin/bash

set -ex

NAME=mds-throughput

RAW="$NAME.raw"
DATA="$NAME.dat"
GRAPH="$NAME.eps"

if ! [ -f "$RAW" ]; then
(
    for mds in "$@"; do
        sqlite3 -separator $'\t' -noheader "$mds" <<EOF
SELECT MDSStatus.timestamp, json_extract(MDSStatus.status, '$.whoami') AS rank, json_extract(MDSStatus.perf_dump, '$.mds.reply')
    FROM MDSStatus
    WHERE rank >= 0 AND rank != 18446744073709551615
    ORDER BY MDSStatus.timestamp
    ;
EOF
    done
) > "$RAW"
fi

# one data point per second
lua "$(dirname "$0")/tfix-dy.lua" < "$RAW" > "$DATA"

gnuplot <<EOF
set datafile separator "\\t"
set terminal postscript eps color
set output '${GRAPH}'

DATA = "${DATA}"

stats DATA skip 1
# using floor to convert float to int
COL = floor(STATS_columns)

set xdata time
set timefmt "%s"
set format x "%H:%M"
set xlabel "Time (hh:mm)"
set xtics rotate by -45 offset -.8,0

set key below title "MDS Rank"

set ylabel "Client Request Throughput (ops/second)"
set mytics

#get(name, i) = value(sprintf("_%s_%i", name, i))
#set(name, i, value) = sprintf("_%s_%i = %.16e", name, i, value)
#d(ycol) = (\$0 == 0) ? (set('y1', ycol, column(ycol)), 1/0) : (set('y2', ycol, get('y1', ycol)), set('y1', ycol, column(ycol)), get('y1', ycol)-get('y2', ycol))
#dx = 0.5

#d(y) = (\$0 == 0) ? (y1 = y, 1/0) : (y2 = y1, y1 = y, y1-y2)
#dx = 0.5

plot [0:][0:] for [i=2:COL] DATA using 1:(sum [col=i:COL] column(col)) smooth csplines with filledcurves x1 title columnheader(i)
EOF

convert -flatten -density 800x800 "$GRAPH" "$(dirname "$GRAPH")/$(basename "$GRAPH" .eps).png"
