#!/bin/bash

set -ex

DATA="$(dirname "$1")/mdsmem.txt"
GRAPH="$(dirname "$1")/mdsmem-rss.eps"

sqlite3 -csv "$1" > "$DATA" <<EOF
WITH
    mds_mem AS (
        SELECT MDSStatus.*, json_extract(MDSStatus.perf_dump, '$.mds_mem') AS j
            FROM MDSStatus
    )
SELECT timestamp, json_extract(mds_mem.j, '$.ino'), json_extract(j, '$.rss')
    FROM mds_mem
    ;
EOF

gnuplot <<EOF
set datafile separator ","
set terminal postscript eps mono
set output '${GRAPH}'

stats "${DATA}" using 1 prefix "timestamp" nooutput

set xdata time
set timefmt "%s"
set format x "%H:%M"
set xlabel "Time (hh:mm)"
set xtics rotate by -45 offset -.8,0

set ylabel "RSS (KB)"
set mytics

plot [][0:] "${DATA}" using (\$1-timestamp_min):3 title "Memory Used (KB)"
EOF

convert -flatten -density 800x800 "$GRAPH" "$(dirname "$GRAPH")/$(basename "$GRAPH" .eps).png"
