#!/bin/bash

set -ex

NAME=osd-memory

RAW="$1/$NAME.raw"
DATA="$1/$NAME.dat"
GRAPH="$1/$NAME.eps"

if ! [ -f "$RAW" ]; then
(
    cd "$1"
    for osd in *osd-[0-9]*; do
        sqlite3 -separator $'\t' -noheader "$osd/stats.db" <<EOF
SELECT OSDStatus.timestamp, json_extract(OSDStatus.status, '$.whoami') AS rank, MAX(rss)*4096
    FROM OSDStatus JOIN DaemonStats ON DaemonStats.id = OSDStatus.id AND DaemonStats.timestamp = OSDStatus.timestamp
    WHERE rank >= 0 AND rank != 18446744073709551615
    GROUP BY OSDStatus.id, OSDStatus.timestamp
    ORDER BY OSDStatus.timestamp
    ;
EOF
    done
) > "$RAW"
fi

# one data point per second
lua "$(dirname "$0")/tfix.lua" < "$RAW" > "$DATA"

gnuplot <<EOF
set datafile separator "\\t"
set terminal postscript eps color
set output '${GRAPH}'

DATA = "${DATA}"

stats DATA skip 1
# using floor to convert float to int
COL = floor(STATS_columns)

set xdata time
set timefmt "%s"
set format x "%H:%M"
set xlabel "Time (hh:mm)"
set xtics rotate by -45 offset -.8,0

set key below title "OSD id"

set ylabel "Memory Use (MB)"
set mytics

plot for [i=2:COL] DATA using 1:(sum [col=i:COL] column(col)/(1024*1024)) with filledcurves x1 title columnheader(i)
EOF

convert -flatten -density 800x800 "$GRAPH" "$(dirname "$GRAPH")/$(basename "$GRAPH" .eps).png"
